services:
  - type: web
    name: ocr-odoo-fullstack
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_VERSION
        value: 9.6.7
    healthCheckPath: /api/health