services:
  - type: web
    name: ocr-odoo-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements_render.txt
    startCommand: |
      cd backend
      python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /api/health